CLASS LHC_ZR_RAP_TRAVEL_NEW DEFINITION INHERITING FROM CL_ABAP_BEHAVIOR_HANDLER.
  PRIVATE SECTION.
    METHODS:
      GET_GLOBAL_AUTHORIZATIONS FOR GLOBAL AUTHORIZATION
        IMPORTING
           REQUEST requested_authorizations FOR ZI_TRAVEL_TEST
        RESULT result.
ENDCLASS.

CLASS LHC_ZR_RAP_TRAVEL_NEW IMPLEMENTATION.
  METHOD GET_GLOBAL_AUTHORIZATIONS.
  ENDMETHOD.
ENDCLASS.
