CLASS zbp_i_dpl_header DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF zi_dpl_header.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS zbp_i_dpl_header IMPLEMENTATION.
ENDCLASS.
